export * from './etherscan.interfaces';
export * from './uniswap.interfaces';
export * from './parser/calculateBalance.interface';
export * from './parser/calculateTransaction.interface';
export * from './parser/calculateVolumes';
export * from './parser/commonJob.interface';
export * from './parser/parseWallet.interface';
export * from './parser/tradesBuilderV2.interface';
export * from './main.interfaces';
